- name: Update apt packages
  become: yes
  apt:
    update_cache: yes

- name: Upgrade packages
  become: yes
  apt:
    upgrade: yes

- name: Install unzip
  become: yes
  apt:
    name: unzip
    state: latest

- name: Install node
  become: yes
  apt:
    name: nodejs
    state: latest

- name: Install npm
  become: yes
  apt:
    name: npm
    state: latest

- name: Install PM2
  become: yes
  shell: npm install pm2 -g
